### ISSUE TITLE
Assignments - Spring 2020

### ISSUE THREAD

**Issue by jebeckford** [cloudmesh-community/sp20-516-237#2]
```

Assignments
* [x] Verify you have access to piazza, github, 
* [x] Bio in piazza (Jan 17, 2020)
* [x] Fill out Zoom poll
* [x] Fill out Class Survey
* [x] GitHub account (Not your IU GitHub account !)
* [x] Chameleon account
* [x] Install python 3.8 and pip 19.3.1 (or greater)
### TODO: Everything below here needs to be revised
* [ ] Big Data
* [ ] Technology
* [ ] Tutorial
* [ ] Propose unique tutorial topic
* [ ] write tutorial in md
* [ ] convert tutorial to tex with pandoc and cleanup
* [ ] verify integration
* [ ] have another student verify tutorial
* [ ] have TA verify tutorial
* [ ] Cloud Rest Services
* [ ] REST

```
